/**
 * Per-parcel detail without the 133 MB parcel file.
 *
 * Parcels draw from vector tiles (see DeckLayers.ts); when someone clicks
 * one we fetch a small per-parcel JSON from Cloud Storage that carries the
 * full geometry plus the building footprints on or beside it. A ~1 MB bbox
 * index (`/data/parcel_index.json`) answers "which parcel is at this point"
 * for shared-link restores and address searches, and supplies FID → tax
 * area for the island greenery percentiles. Both files are generated by
 * scripts/build-parcel-files.py.
 */
import * as turf from '@turf/turf';

const BASE = 'https://storage.googleapis.com/salish-ndvi-tiles/parcels';
const INDEX_URL = '/data/parcel_index.json';

export type ParcelPolygon = GeoJSON.Feature<GeoJSON.Polygon | GeoJSON.MultiPolygon>;

export interface ParcelDetail {
  parcel: ParcelPolygon;
  buildings: GeoJSON.Feature[];
}

/** FID → [minLng, minLat, maxLng, maxLat, Tax_Area, PIN] */
export type ParcelIndex = Record<string, [number, number, number, number, string, string]>;

const detailCache = new Map<string, Promise<ParcelDetail | null>>();
let indexPromise: Promise<ParcelIndex> | null = null;

export function fetchParcelDetail(fid: string | number): Promise<ParcelDetail | null> {
  const key = String(fid);
  let p = detailCache.get(key);
  if (!p) {
    p = fetch(`${BASE}/${encodeURIComponent(key)}.json`)
      .then(r => (r.ok ? (r.json() as Promise<ParcelDetail>) : null))
      .then(d => (d && d.parcel?.geometry && (d.parcel.geometry.type === 'Polygon' || d.parcel.geometry.type === 'MultiPolygon') ? d : null))
      .catch(() => null);
    detailCache.set(key, p);
  }
  return p;
}

export function getParcelIndex(): Promise<ParcelIndex> {
  if (!indexPromise) {
    indexPromise = fetch(INDEX_URL)
      .then(r => (r.ok ? (r.json() as Promise<ParcelIndex>) : {}))
      .catch(() => ({}));
  }
  return indexPromise;
}

/** FID → Tax_Area (island) for every parcel, from the index. */
export async function getFidToTaxArea(): Promise<Map<string, string>> {
  const idx = await getParcelIndex();
  const m = new Map<string, string>();
  for (const [fid, row] of Object.entries(idx)) {
    if (row[4]) m.set(fid, row[4]);
  }
  return m;
}

/** The parcel containing a point: bbox candidates from the index, then a real point-in-polygon test. */
export async function findParcelAtPoint(lat: number, lng: number): Promise<{ fid: string; detail: ParcelDetail } | null> {
  const idx = await getParcelIndex();
  const candidates: string[] = [];
  for (const [fid, [minLng, minLat, maxLng, maxLat]] of Object.entries(idx)) {
    if (lng >= minLng && lng <= maxLng && lat >= minLat && lat <= maxLat) candidates.push(fid);
  }
  if (candidates.length === 0) return null;
  const pt = turf.point([lng, lat]);
  const details = await Promise.all(candidates.slice(0, 12).map(fid => fetchParcelDetail(fid).then(d => ({ fid, d }))));
  for (const { fid, d } of details) {
    if (!d) continue;
    try {
      if (turf.booleanPointInPolygon(pt, d.parcel)) return { fid, detail: d };
    } catch {
      continue;
    }
  }
  return null;
}
