import type { LayerConfig } from '../types';

export const layerConfigs: LayerConfig[] = [
  // === Property Layers ===
  {
    id: 'tax-parcels',
    name: 'Tax Parcels',
    description: 'Property boundaries from San Juan County Assessor',
    category: 'property',
    source: '/data/Tax_Parcels.geojson',
    visible: true,
    style: {
      fillColor: '#ADB5BD',
      fillOpacity: 0.05,
      strokeColor: '#F97316',
      strokeWeight: 1.2,
    },
    popupFields: [
      { key: 'PIN', label: 'Parcel ID' },
      { key: 'Short_Lega', label: 'Legal Description' },
      { key: 'Acres', label: 'Acres' },
      { key: 'Tax_Area', label: 'Tax Area' },
      { key: 'Land_Value', label: 'Land Value' },
      { key: 'Appraised_', label: 'Appraised Value' },
      { key: 'Bldg_Value', label: 'Building Value' },
      { key: 'Use_Code', label: 'Use Code' },
      { key: 'Descriptio', label: 'Description' },
      { key: 'Sale_date', label: 'Last Sale Date' },
      { key: 'Sale_Price', label: 'Last Sale Price' },
    ],
    minZoom: 15,
    viewportFiltered: true,
  },
  {
    id: 'building-footprints',
    name: 'Building Footprints',
    description: 'Building footprints across San Juan County',
    category: 'property',
    source: '/data/Building_Footprints.geojson',
    visible: true,
    style: {
      fillColor: '#60A5FA',
      fillOpacity: 0.7,
      strokeColor: '#1A252F',
      strokeWeight: 0.8,
    },
    popupFields: [
      { key: 'ADDRESS', label: 'Address' },
      { key: 'Sq_Ft', label: 'Footprint (sq ft)' },
      { key: 'Island', label: 'Island' },
      { key: 'PIN', label: 'Parcel PIN' },
      { key: 'Discriptio', label: 'Description' },
      { key: 'Source', label: 'Data Source' },
    ],
    minZoom: 15,
    viewportFiltered: true,
  },

  // === Planning Layers ===
  {
    id: 'stormwater-pipes',
    name: 'Stormwater Infrastructure',
    description: 'County stormwater pipe network',
    category: 'planning',
    source: '/data/Stormwater_Pipes.geojson',
    visible: true,
    minZoom: 15,
    style: {
      fillColor: '#E67E22',
      fillOpacity: 0,
      strokeColor: '#E67E22',
      strokeWeight: 2.5,
    },
    popupFields: [
      { key: 'Pipe_ID', label: 'Pipe ID' },
      { key: 'Diameter', label: 'Diameter (in)' },
      { key: 'Material', label: 'Material' },
      { key: 'Length', label: 'Length (ft)' },
      { key: 'Pipe_Class', label: 'Class' },
      { key: 'Island', label: 'Island' },
      { key: 'Status', label: 'Status' },
      { key: 'Instl_Year', label: 'Install Year' },
    ],
    standardMessage: 'Stormwater infrastructure carries runoff from roads and developed areas to nearby water bodies. Pollutants in stormwater—oils, heavy metals, nutrients—can degrade nearshore habitat quality for salmon, forage fish, and shellfish.',
  },

  // === Fish Habitat Layers ===
  {
    id: 'chinook-salmon',
    name: 'Chinook Salmon',
    description: 'Shoreline habitat relevance for Chinook salmon',
    category: 'fish-habitat',
    source: '/data/chinook-salmon.geojson',
    visible: false,
    style: {
      fillColor: '#DC2626',
      fillOpacity: 0,
      strokeColor: '#DC2626',
      strokeWeight: 2.5,
    },
    popupFields: [
      { key: 'Name', label: 'Location' },
      { key: 'HRM_Ck', label: 'Habitat Relevance (High)' },
      { key: 'LRM_Ck', label: 'Habitat Relevance (Low)' },
      { key: 'GeoUnit', label: 'Geomorphic Unit' },
      { key: 'RITT_SysTy', label: 'System Type' },
      { key: 'RITT_SubTy', label: 'Sub Type' },
    ],
    standardMessage: 'Chinook salmon are listed as threatened under the Endangered Species Act. Nearshore habitat is critical for juvenile Chinook rearing and migration. Shoreline modification can reduce prey availability and disrupt migration corridors.',
  },
  {
    id: 'chum-salmon',
    name: 'Chum Salmon',
    description: 'Shoreline habitat relevance for Chum salmon',
    category: 'fish-habitat',
    source: '/data/chum-salmon.geojson',
    visible: false,
    style: {
      fillColor: '#7C3AED',
      fillOpacity: 0,
      strokeColor: '#7C3AED',
      strokeWeight: 2.5,
    },
    popupFields: [
      { key: 'Name', label: 'Location' },
      { key: 'HRM_Chum', label: 'Habitat Relevance (High)' },
      { key: 'LRM_Chum', label: 'Habitat Relevance (Low)' },
      { key: 'GeoUnit', label: 'Geomorphic Unit' },
      { key: 'RITT_SysTy', label: 'System Type' },
      { key: 'RITT_SubTy', label: 'Sub Type' },
    ],
    standardMessage: 'Chum salmon depend on nearshore habitats during early marine life stages. Estuaries and pocket beaches provide critical transition zones where juveniles feed and grow before moving offshore.',
  },
  {
    id: 'pink-salmon',
    name: 'Pink Salmon',
    description: 'Shoreline habitat relevance for Pink salmon',
    category: 'fish-habitat',
    source: '/data/pink-salmon.geojson',
    visible: false,
    style: {
      fillColor: '#EC4899',
      fillOpacity: 0,
      strokeColor: '#EC4899',
      strokeWeight: 2.5,
    },
    popupFields: [
      { key: 'Name', label: 'Location' },
      { key: 'HRM_Pk', label: 'Habitat Relevance (High)' },
      { key: 'LRM_Pk', label: 'Habitat Relevance (Low)' },
      { key: 'GeoUnit', label: 'Geomorphic Unit' },
      { key: 'RITT_SysTy', label: 'System Type' },
      { key: 'RITT_SubTy', label: 'Sub Type' },
    ],
    standardMessage: 'Pink salmon are the most abundant Pacific salmon species. Their juveniles spend minimal time in freshwater, making nearshore marine habitat especially critical during outmigration.',
  },
  {
    id: 'pacific-herring',
    name: 'Pacific Herring',
    description: 'Shoreline habitat relevance for Pacific herring',
    category: 'fish-habitat',
    source: '/data/pacific-herring.geojson',
    visible: false,
    style: {
      fillColor: '#EAB308',
      fillOpacity: 0,
      strokeColor: '#EAB308',
      strokeWeight: 2.5,
    },
    popupFields: [
      { key: 'Name', label: 'Location' },
      { key: 'HRM_Herr', label: 'Habitat Relevance (High)' },
      { key: 'LRM_Herr', label: 'Habitat Relevance (Low)' },
      { key: 'GeoUnit', label: 'Geomorphic Unit' },
      { key: 'RITT_SysTy', label: 'System Type' },
      { key: 'RITT_SubTy', label: 'Sub Type' },
    ],
    standardMessage: 'Pacific herring are a keystone forage fish species, spawning on eelgrass and algae in nearshore areas. Herring are a primary food source for salmon, seabirds, and marine mammals throughout the Salish Sea.',
  },
  {
    id: 'pacific-sand-lance',
    name: 'Pacific Sand Lance',
    description: 'Shoreline habitat relevance for Pacific sand lance',
    category: 'fish-habitat',
    source: '/data/pacific-sand-lance.geojson',
    visible: false,
    style: {
      fillColor: '#F97316',
      fillOpacity: 0,
      strokeColor: '#F97316',
      strokeWeight: 2.5,
    },
    popupFields: [
      { key: 'Name', label: 'Location' },
      { key: 'HRM_Lance', label: 'Habitat Relevance (High)' },
      { key: 'LRM_Lance', label: 'Habitat Relevance (Low)' },
      { key: 'GeoUnit', label: 'Geomorphic Unit' },
      { key: 'RITT_SysTy', label: 'System Type' },
      { key: 'RITT_SubTy', label: 'Sub Type' },
    ],
    standardMessage: 'Sand lance spawn in the upper intertidal zone on sand-gravel beaches. Shoreline armoring and beach modification directly destroy spawning habitat for this essential forage fish.',
  },
  {
    id: 'surf-smelt',
    name: 'Surf Smelt',
    description: 'Shoreline habitat relevance for Surf smelt',
    category: 'fish-habitat',
    source: '/data/surf-smelt.geojson',
    visible: false,
    style: {
      fillColor: '#06B6D4',
      fillOpacity: 0,
      strokeColor: '#06B6D4',
      strokeWeight: 2.5,
    },
    popupFields: [
      { key: 'Name', label: 'Location' },
      { key: 'HRM_Smelt', label: 'Habitat Relevance (High)' },
      { key: 'LRM_Smelt', label: 'Habitat Relevance (Low)' },
      { key: 'GeoUnit', label: 'Geomorphic Unit' },
      { key: 'RITT_SysTy', label: 'System Type' },
      { key: 'RITT_SubTy', label: 'Sub Type' },
    ],
    standardMessage: 'Surf smelt spawn on mixed sand-gravel beaches in the upper intertidal zone. Like sand lance, their spawning habitat is directly threatened by shoreline hardening and development.',
  },
  {
    id: 'lingcod-greenling',
    name: 'Lingcod & Greenling',
    description: 'Shoreline habitat relevance for Lingcod and Greenling (Hexagrammidae)',
    category: 'fish-habitat',
    source: '/data/lingcod-greenling.geojson',
    visible: false,
    style: {
      fillColor: '#65A30D',
      fillOpacity: 0,
      strokeColor: '#65A30D',
      strokeWeight: 2.5,
    },
    popupFields: [
      { key: 'Name', label: 'Location' },
      { key: 'HRM_Hex', label: 'Habitat Relevance (High)' },
      { key: 'LRM_Hex', label: 'Habitat Relevance (Low)' },
      { key: 'GeoUnit', label: 'Geomorphic Unit' },
      { key: 'RITT_SysTy', label: 'System Type' },
      { key: 'RITT_SubTy', label: 'Sub Type' },
    ],
    standardMessage: 'Lingcod and greenling use rocky nearshore habitats for spawning and juvenile rearing. Kelp forests and rocky reefs are essential for their life cycle.',
  },

  // === Ecological Layers ===
  {
    id: 'ndvi',
    name: 'Vegetation Health (NDVI)',
    description: 'Normalized Difference Vegetation Index derived from NAIP aerial imagery (Oct 2023, 0.6m resolution)',
    category: 'ecological',
    source: '',
    visible: false,
    style: {
      fillColor: '#1a9850',
      fillOpacity: 0,
      strokeColor: '#1a9850',
      strokeWeight: 0,
    },
    popupFields: [],
    standardMessage: 'NDVI measures vegetation density and health from aerial imagery. Green areas indicate healthy, dense vegetation; yellow indicates sparse or stressed vegetation; red indicates bare ground, water, or impervious surfaces.',
    layerType: 'raster',
    tileUrl: 'https://storage.googleapis.com/salish-ndvi-tiles/ndvi/{z}/{x}/{y}.png',
    defaultOpacity: 0.7,
    minZoom: 10,
  },
  {
    id: 'ndvi-sentinel',
    name: 'Sentinel-2 NDVI (10m)',
    description: 'Sentinel-2 derived NDVI at 10m resolution — select a date range to view seasonal vegetation change',
    category: 'ecological',
    source: '',
    visible: false,
    style: {
      fillColor: '#1a9850',
      fillOpacity: 0,
      strokeColor: '#1a9850',
      strokeWeight: 0,
    },
    popupFields: [],
    standardMessage: 'Sentinel-2 NDVI computed on-the-fly from cloud-free satellite composites. Use the date range controls to compare vegetation health across seasons and years.',
    layerType: 'dynamic-raster',
    apiEndpoint: 'https://us-west1-salish-sea-property-mapper.cloudfunctions.net/ee-ndvi-tiles',
    defaultOpacity: 0.7,
    minZoom: 10,
  },
  {
    id: 'eelgrass',
    name: 'Eelgrass Beds',
    description: 'Mapped eelgrass (Zostera marina) presence in nearshore areas',
    category: 'ecological',
    source: '/data/eelgrass.geojson',
    visible: true,
    style: {
      fillColor: '#2D6A4F',
      fillOpacity: 0.4,
      strokeColor: '#1B4332',
      strokeWeight: 1,
    },
    popupFields: [
      { key: 'survey_year', label: 'Survey Year' },
      { key: 'density', label: 'Density Class' },
      { key: 'area_sqm', label: 'Area (sq m)' },
    ],
    standardMessage: 'Eelgrass beds are critical nursery habitat for juvenile salmon, forage fish, and Dungeness crab. They also sequester carbon and stabilize shoreline sediments. Development or activity that disturbs eelgrass is regulated under the Shoreline Management Act.',
    placeholder: true,
  },
  {
    id: 'shoreline-types',
    name: 'Shoreline Types',
    description: 'Classification of shoreline character and substrate',
    category: 'ecological',
    source: '/data/shoreline_types.geojson',
    visible: true,
    style: {
      fillColor: '#0D4F4F',
      fillOpacity: 0,
      strokeColor: '#0D4F4F',
      strokeWeight: 2,
    },
    popupFields: [
      { key: 'shore_type', label: 'Shoreline Type' },
      { key: 'substrate', label: 'Substrate' },
    ],
    standardMessage: 'Shoreline character—whether rocky, sandy, or mixed—determines what species can thrive there. Armoring or modifying natural shorelines disrupts sediment transport and eliminates habitat for forage fish spawning.',
    placeholder: true,
  },
  {
    id: 'habitat-zones',
    name: 'Habitat Zones',
    description: 'Sensitive habitat areas identified through conservation research',
    category: 'ecological',
    source: '/data/habitat_zones.geojson',
    visible: true,
    style: {
      fillColor: '#D4A574',
      fillOpacity: 0.3,
      strokeColor: '#B8865A',
      strokeWeight: 1,
    },
    popupFields: [
      { key: 'habitat_type', label: 'Habitat Type' },
      { key: 'species', label: 'Key Species' },
      { key: 'sensitivity', label: 'Sensitivity' },
    ],
    standardMessage: 'These zones have been identified as ecologically sensitive through surveys and conservation research. Activities in or near these areas may require additional review under local critical areas ordinances.',
    placeholder: true,
  },
];

export const categoryLabels: Record<string, string> = {
  'fish-habitat': 'Fish Habitat',
  ecological: 'Ecological',
  property: 'Property',
  'community-science': 'Community Science',
  planning: 'Planning & Infrastructure',
};

export const categoryOrder = ['fish-habitat', 'ecological', 'property', 'planning', 'community-science'];
