import type { LayerConfig } from '../types';

export const layerConfigs: LayerConfig[] = [
  // === Property Layers ===
  {
    id: 'tax-parcels',
    name: 'Tax Parcels',
    description: 'Property boundaries from San Juan County Assessor',
    category: 'property',
    source: 'https://storage.googleapis.com/salish-ndvi-tiles/data/Tax_Parcels.geojson',
    visible: true,
    style: {
      fillColor: '#ADB5BD',
      fillOpacity: 0.05,
      strokeColor: '#F97316',
      strokeWeight: 1.2,
    },
    popupFields: [
      { key: 'PIN', label: 'Parcel ID' },
      { key: 'Short_Lega', label: 'Legal Description' },
      { key: 'Acres', label: 'Acres' },
      { key: 'Tax_Area', label: 'Tax Area' },
      { key: 'Land_Value', label: 'Land Value' },
      { key: 'Appraised_', label: 'Appraised Value' },
      { key: 'Bldg_Value', label: 'Building Value' },
      { key: 'Use_Code', label: 'Use Code' },
      { key: 'Descriptio', label: 'Description' },
      { key: 'Sale_date', label: 'Last Sale Date' },
      { key: 'Sale_Price', label: 'Last Sale Price' },
    ],
    minZoom: 15,
    viewportFiltered: true,
  },
  {
    id: 'building-footprints',
    name: 'Building Footprints',
    description: 'Building footprints across San Juan County',
    category: 'property',
    source: '/data/Building_Footprints.geojson',
    visible: true,
    style: {
      fillColor: '#60A5FA',
      fillOpacity: 0.7,
      strokeColor: '#1A252F',
      strokeWeight: 0.8,
    },
    popupFields: [
      { key: 'ADDRESS', label: 'Address' },
      { key: 'Sq_Ft', label: 'Footprint (sq ft)' },
      { key: 'Island', label: 'Island' },
      { key: 'PIN', label: 'Parcel PIN' },
      { key: 'Discriptio', label: 'Description' },
      { key: 'Source', label: 'Data Source' },
    ],
    minZoom: 15,
    viewportFiltered: true,
  },

  // === Planning Layers ===
  {
    id: 'stormwater-pipes',
    name: 'Stormwater Infrastructure',
    description: 'County stormwater pipe network',
    category: 'planning',
    source: '/data/Stormwater_Pipes.geojson',
    visible: true,
    minZoom: 15,
    style: {
      fillColor: '#E67E22',
      fillOpacity: 0,
      strokeColor: '#E67E22',
      strokeWeight: 2.5,
    },
    popupFields: [
      { key: 'Pipe_ID', label: 'Pipe ID' },
      { key: 'Diameter', label: 'Diameter (in)' },
      { key: 'Material', label: 'Material' },
      { key: 'Length', label: 'Length (ft)' },
      { key: 'Pipe_Class', label: 'Class' },
      { key: 'Island', label: 'Island' },
      { key: 'Status', label: 'Status' },
      { key: 'Instl_Year', label: 'Install Year' },
    ],
    standardMessage: 'Stormwater infrastructure carries runoff from roads and developed areas to nearby water bodies. Pollutants in stormwater—oils, heavy metals, nutrients—can degrade nearshore habitat quality for salmon, forage fish, and shellfish.',
  },

  // === Fish Habitat Layers ===
  {
    id: 'chinook-salmon',
    name: 'Chinook Salmon',
    description: 'Shoreline habitat relevance for Chinook salmon',
    category: 'fish-habitat',
    source: '/data/chinook-salmon.geojson',
    visible: false,
    style: {
      fillColor: '#DC2626',
      fillOpacity: 0,
      strokeColor: '#DC2626',
      strokeWeight: 2.5,
    },
    popupFields: [
      { key: 'Name', label: 'Location' },
      { key: 'HRM_Ck', label: 'Habitat Relevance (High)' },
      { key: 'LRM_Ck', label: 'Habitat Relevance (Low)' },
      { key: 'GeoUnit', label: 'Geomorphic Unit' },
      { key: 'RITT_SysTy', label: 'System Type' },
      { key: 'RITT_SubTy', label: 'Sub Type' },
    ],
    standardMessage: 'Chinook salmon are listed as threatened under the Endangered Species Act. Nearshore habitat is critical for juvenile Chinook rearing and migration. Shoreline modification can reduce prey availability and disrupt migration corridors.',
  },
  {
    id: 'chum-salmon',
    name: 'Chum Salmon',
    description: 'Shoreline habitat relevance for Chum salmon',
    category: 'fish-habitat',
    source: '/data/chum-salmon.geojson',
    visible: false,
    style: {
      fillColor: '#7C3AED',
      fillOpacity: 0,
      strokeColor: '#7C3AED',
      strokeWeight: 2.5,
    },
    popupFields: [
      { key: 'Name', label: 'Location' },
      { key: 'HRM_Chum', label: 'Habitat Relevance (High)' },
      { key: 'LRM_Chum', label: 'Habitat Relevance (Low)' },
      { key: 'GeoUnit', label: 'Geomorphic Unit' },
      { key: 'RITT_SysTy', label: 'System Type' },
      { key: 'RITT_SubTy', label: 'Sub Type' },
    ],
    standardMessage: 'Chum salmon depend on nearshore habitats during early marine life stages. Estuaries and pocket beaches provide critical transition zones where juveniles feed and grow before moving offshore.',
  },
  {
    id: 'pink-salmon',
    name: 'Pink Salmon',
    description: 'Shoreline habitat relevance for Pink salmon',
    category: 'fish-habitat',
    source: '/data/pink-salmon.geojson',
    visible: false,
    style: {
      fillColor: '#EC4899',
      fillOpacity: 0,
      strokeColor: '#EC4899',
      strokeWeight: 2.5,
    },
    popupFields: [
      { key: 'Name', label: 'Location' },
      { key: 'HRM_Pk', label: 'Habitat Relevance (High)' },
      { key: 'LRM_Pk', label: 'Habitat Relevance (Low)' },
      { key: 'GeoUnit', label: 'Geomorphic Unit' },
      { key: 'RITT_SysTy', label: 'System Type' },
      { key: 'RITT_SubTy', label: 'Sub Type' },
    ],
    standardMessage: 'Pink salmon are the most abundant Pacific salmon species. Their juveniles spend minimal time in freshwater, making nearshore marine habitat especially critical during outmigration.',
  },
  {
    id: 'pacific-herring',
    name: 'Pacific Herring',
    description: 'Shoreline habitat relevance for Pacific herring',
    category: 'fish-habitat',
    source: '/data/pacific-herring.geojson',
    visible: false,
    style: {
      fillColor: '#EAB308',
      fillOpacity: 0,
      strokeColor: '#EAB308',
      strokeWeight: 2.5,
    },
    popupFields: [
      { key: 'Name', label: 'Location' },
      { key: 'HRM_Herr', label: 'Habitat Relevance (High)' },
      { key: 'LRM_Herr', label: 'Habitat Relevance (Low)' },
      { key: 'GeoUnit', label: 'Geomorphic Unit' },
      { key: 'RITT_SysTy', label: 'System Type' },
      { key: 'RITT_SubTy', label: 'Sub Type' },
    ],
    standardMessage: 'Pacific herring are a keystone forage fish species, spawning on eelgrass and algae in nearshore areas. Herring are a primary food source for salmon, seabirds, and marine mammals throughout the Salish Sea.',
  },
  {
    id: 'pacific-sand-lance',
    name: 'Pacific Sand Lance',
    description: 'Shoreline habitat relevance for Pacific sand lance',
    category: 'fish-habitat',
    source: '/data/pacific-sand-lance.geojson',
    visible: false,
    style: {
      fillColor: '#F97316',
      fillOpacity: 0,
      strokeColor: '#F97316',
      strokeWeight: 2.5,
    },
    popupFields: [
      { key: 'Name', label: 'Location' },
      { key: 'HRM_Lance', label: 'Habitat Relevance (High)' },
      { key: 'LRM_Lance', label: 'Habitat Relevance (Low)' },
      { key: 'GeoUnit', label: 'Geomorphic Unit' },
      { key: 'RITT_SysTy', label: 'System Type' },
      { key: 'RITT_SubTy', label: 'Sub Type' },
    ],
    standardMessage: 'Sand lance spawn in the upper intertidal zone on sand-gravel beaches. Shoreline armoring and beach modification directly destroy spawning habitat for this essential forage fish.',
  },
  {
    id: 'surf-smelt',
    name: 'Surf Smelt',
    description: 'Shoreline habitat relevance for Surf smelt',
    category: 'fish-habitat',
    source: '/data/surf-smelt.geojson',
    visible: false,
    style: {
      fillColor: '#06B6D4',
      fillOpacity: 0,
      strokeColor: '#06B6D4',
      strokeWeight: 2.5,
    },
    popupFields: [
      { key: 'Name', label: 'Location' },
      { key: 'HRM_Smelt', label: 'Habitat Relevance (High)' },
      { key: 'LRM_Smelt', label: 'Habitat Relevance (Low)' },
      { key: 'GeoUnit', label: 'Geomorphic Unit' },
      { key: 'RITT_SysTy', label: 'System Type' },
      { key: 'RITT_SubTy', label: 'Sub Type' },
    ],
    standardMessage: 'Surf smelt spawn on mixed sand-gravel beaches in the upper intertidal zone. Like sand lance, their spawning habitat is directly threatened by shoreline hardening and development.',
  },
  {
    // Marbled murrelet is a seabird, not a fish, but WDFW's at-sea boat surveys
    // (MRB) and aerial surveys (PSEMP) produce stratum-level density estimates
    // analogous in shape to the fish-habitat layers, so the layer is grouped
    // with the marine wildlife datasets. Density values are stratum aggregates,
    // not point observations; the 30m raster products cataloged in
    // `public/data/wdfw_*_mosaic_catalog.json` are interpolated display
    // surfaces and are not rendered here. Coverage is US Salish Sea only —
    // does not extend into BC waters. Source: WDFW Wildlife Program; we will
    // need separate attribution + use permission (Scott Pearson group) before
    // public deployment.
    id: 'marbled-murrelet-breeding',
    name: 'Marbled Murrelet (Breeding Season)',
    description:
      'WDFW Marine Resident Seabird (MRB) boat-survey density estimates for marbled murrelet, May 15 – Jul 31. Stratum-aggregated; 3 strata × annual estimates 2001–2020.',
    category: 'fish-habitat',
    source: '/data/mamu_mrb_density_by_stratum_year.geojson',
    visible: false,
    style: {
      fillColor: '#B45309',
      fillOpacity: 0.25,
      strokeColor: '#92400E',
      strokeWeight: 1.5,
    },
    popupFields: [
      { key: 'StrataName', label: 'Stratum' },
      { key: 'latestYear', label: 'Latest Survey Year' },
      { key: 'EstBirds_latest', label: 'Estimated Birds' },
      { key: 'Lower_latest', label: '95% CI Lower' },
      { key: 'Upper_latest', label: '95% CI Upper' },
      { key: 'Density_latest', label: 'Density (birds/km²)' },
      { key: 'Density_CV_latest', label: 'Density CV' },
    ],
    standardMessage:
      'Marbled murrelets are listed as Threatened under the federal Endangered Species Act. These values are spring/summer at-sea density estimates from WDFW boat surveys (MRB), aggregated to large biogeographic strata — they represent abundance for the stratum as a whole, not the point you clicked. The companion 30m raster surfaces published by WDFW are interpolated display products, not raw observations.',
    sourceUrl:
      'https://geodataservices.wdfw.wa.gov/arcgis/rest/services/WP_WildlifeSurveys/MRB/MapServer',
  },
  {
    // Winter aerial counterpart to the MRB breeding layer. Same caveats:
    // stratum-aggregated, US Salish Sea only, raster surfaces are
    // interpolated. PSEMP Stats uses Median/Lower_90/Upper_90 (bootstrap CI)
    // rather than MRB's EstBirds/Lower/Upper (normal-CL CI).
    id: 'marbled-murrelet-winter',
    name: 'Marbled Murrelet (Winter)',
    description:
      'WDFW Puget Sound Ecosystem Monitoring Program (PSEMP) winter aerial-survey density estimates for marbled murrelet. Stratum-aggregated; 36 basins × annual estimates 1996–2024.',
    category: 'fish-habitat',
    source:
      'https://storage.googleapis.com/salish-ndvi-tiles/data/mamu_psemp_density_by_stratum_year.geojson',
    visible: false,
    style: {
      fillColor: '#475569',
      fillOpacity: 0.25,
      strokeColor: '#1E293B',
      strokeWeight: 1.5,
    },
    popupFields: [
      { key: 'StrataName', label: 'Basin' },
      { key: 'Depth_latest', label: 'Depth Stratum' },
      { key: 'sqkm', label: 'Basin Area (km²)' },
      { key: 'latestYear', label: 'Latest Survey Year' },
      { key: 'Median_latest', label: 'Median Estimate (birds)' },
      { key: 'Lower_90_latest', label: '90% CI Lower' },
      { key: 'Upper_90_latest', label: '90% CI Upper' },
      { key: 'Median_Density_latest', label: 'Median Density (birds/km²)' },
    ],
    standardMessage:
      'Marbled murrelets are listed as Threatened under the federal Endangered Species Act. These values are winter at-sea density estimates from PSEMP aerial surveys, aggregated to ~36 basins — they represent abundance for the basin as a whole, not the point you clicked. Confidence intervals are 90% bootstrap rather than 95% normal-CL, reflecting the distance-sampling methodology of the aerial program.',
    sourceUrl:
      'https://geodataservices.wdfw.wa.gov/arcgis/rest/services/WP_WildlifeSurveys/PSEMP/MapServer',
  },
  {
    id: 'lingcod-greenling',
    name: 'Lingcod & Greenling',
    description: 'Shoreline habitat relevance for Lingcod and Greenling (Hexagrammidae)',
    category: 'fish-habitat',
    source: '/data/lingcod-greenling.geojson',
    visible: false,
    style: {
      fillColor: '#65A30D',
      fillOpacity: 0,
      strokeColor: '#65A30D',
      strokeWeight: 2.5,
    },
    popupFields: [
      { key: 'Name', label: 'Location' },
      { key: 'HRM_Hex', label: 'Habitat Relevance (High)' },
      { key: 'LRM_Hex', label: 'Habitat Relevance (Low)' },
      { key: 'GeoUnit', label: 'Geomorphic Unit' },
      { key: 'RITT_SysTy', label: 'System Type' },
      { key: 'RITT_SubTy', label: 'Sub Type' },
    ],
    standardMessage: 'Lingcod and greenling use rocky nearshore habitats for spawning and juvenile rearing. Kelp forests and rocky reefs are essential for their life cycle.',
  },

  // === Ecological Layers ===
  {
    id: 'ndvi',
    name: 'Vegetation Health (NDVI)',
    description: 'Normalized Difference Vegetation Index derived from NAIP aerial imagery (Oct 2023, 0.6m resolution)',
    category: 'ecological',
    source: '',
    visible: false,
    style: {
      fillColor: '#1a9850',
      fillOpacity: 0,
      strokeColor: '#1a9850',
      strokeWeight: 0,
    },
    popupFields: [],
    standardMessage: 'NDVI measures vegetation density and health from aerial imagery. Green areas indicate healthy, dense vegetation; yellow indicates sparse or stressed vegetation; red indicates bare ground, water, or impervious surfaces.',
    layerType: 'raster',
    tileUrl: 'https://storage.googleapis.com/salish-ndvi-tiles/ndvi/{z}/{x}/{y}.png',
    defaultOpacity: 0.7,
    minZoom: 10,
  },
  {
    id: 'ndvi-sentinel',
    name: 'Sentinel-2 NDVI (10m)',
    description: 'Sentinel-2 derived NDVI at 10m resolution — select a date range to view seasonal vegetation change',
    category: 'ecological',
    source: '',
    visible: false,
    style: {
      fillColor: '#1a9850',
      fillOpacity: 0,
      strokeColor: '#1a9850',
      strokeWeight: 0,
    },
    popupFields: [],
    standardMessage: 'Sentinel-2 NDVI computed on-the-fly from cloud-free satellite composites. Use the date range controls to compare vegetation health across seasons and years.',
    layerType: 'dynamic-raster',
    apiEndpoint: 'https://us-west1-salish-sea-property-mapper.cloudfunctions.net/ee-ndvi-tiles',
    defaultOpacity: 0.7,
    minZoom: 10,
  },
  {
    id: 'forest-loss',
    name: 'Forest Loss (2001–2025)',
    description: 'Annual forest cover loss in San Juan County from the Hansen Global Forest Change dataset, derived from Landsat at 30m resolution.',
    category: 'ecological',
    source: '',
    visible: false,
    style: {
      fillColor: '#dc2626',
      fillOpacity: 0,
      strokeColor: '#dc2626',
      strokeWeight: 0,
    },
    popupFields: [],
    standardMessage: 'Annual forest cover loss from the UMD Hansen Global Forest Change dataset. Pixels are colored by the year the loss occurred — pale pink for early loss (2001), bright red for recent loss (2025). Source data is derived from Landsat at 30m resolution. Click any colored pixel for the loss patch size.',
    sourceUrl: 'https://developers.google.com/earth-engine/datasets/catalog/UMD_hansen_global_forest_change_2025_v1_13',
    legend: {
      type: 'gradient',
      colors: ['#fee2e2', '#fecaca', '#fca5a5', '#f87171', '#ef4444', '#dc2626', '#b91c1c'],
      minLabel: '2001',
      maxLabel: '2025',
    },
    layerType: 'dynamic-raster',
    apiEndpoint: 'https://us-west1-salish-sea-property-mapper.cloudfunctions.net/hansen-forest-change',
    hideDateRange: true,
    defaultOpacity: 0.7,
    minZoom: 9,
  },
  {
    id: 'opera-dist-alert',
    name: 'Forest Disturbance (DIST-ALERT)',
    description: 'Near-real-time vegetation disturbance alerts from NASA OPERA L3 DIST-ALERT (HLS, 30m). Updated continuously since 2023.',
    category: 'ecological',
    source: '',
    visible: false,
    style: {
      fillColor: '#dc2626',
      fillOpacity: 0,
      strokeColor: '#dc2626',
      strokeWeight: 0,
    },
    popupFields: [],
    standardMessage: 'Near-real-time forest/vegetation disturbance alerts derived from Harmonized Landsat-Sentinel-2 imagery. Choose a view: Recency shows when each disturbance was detected (bright = recent); Status shows whether an alert is provisional or confirmed; Severity shows the magnitude of vegetation loss (0–100%). Complements the Hansen layer above, which is an annual cumulative product. Detects all vegetation cover loss including agriculture, landslides, and tree clearing; not all alerts are deforestation. Verify before drawing conclusions.',
    sourceUrl: 'https://www.earthdata.nasa.gov/data/catalog/lpcloud-opera-l3-dist-alert-hls-v1-1',
    legend: {
      type: 'gradient',
      colors: ['#450a0a', '#7f1d1d', '#b91c1c', '#dc2626', '#ef4444', '#fb923c', '#fbbf24'],
      minLabel: 'older',
      maxLabel: 'recent',
    },
    layerType: 'dynamic-raster',
    apiEndpoint: 'https://us-west1-salish-sea-property-mapper.cloudfunctions.net/opera-dist-alert',
    hideDateRange: true,
    visualizationModes: [
      {
        id: 'recency',
        label: 'Recency',
        legend: {
          type: 'gradient',
          colors: ['#450a0a', '#7f1d1d', '#b91c1c', '#dc2626', '#ef4444', '#fb923c', '#fbbf24'],
          minLabel: 'older',
          maxLabel: 'recent',
        },
      },
      {
        id: 'status',
        label: 'Status',
        legend: {
          type: 'gradient',
          colors: ['#fde68a', '#fb923c', '#fca5a5', '#ef4444', '#b91c1c', '#7f1d1d'],
          minLabel: 'provisional',
          maxLabel: 'confirmed',
        },
      },
      {
        id: 'severity',
        label: 'Severity',
        legend: {
          type: 'gradient',
          colors: ['#fef3c7', '#fde68a', '#fbbf24', '#fb923c', '#ef4444', '#b91c1c'],
          minLabel: '0%',
          maxLabel: '100% loss',
        },
      },
    ],
    defaultOpacity: 0.75,
    minZoom: 9,
  },
  {
    id: 'eelgrass',
    name: 'Eelgrass Beds',
    description: 'Mapped eelgrass (Zostera marina) presence in nearshore areas',
    category: 'ecological',
    source: '/data/eelgrass.geojson',
    visible: true,
    style: {
      fillColor: '#2D6A4F',
      fillOpacity: 0.4,
      strokeColor: '#1B4332',
      strokeWeight: 1,
    },
    popupFields: [
      { key: 'survey_year', label: 'Survey Year' },
      { key: 'density', label: 'Density Class' },
      { key: 'area_sqm', label: 'Area (sq m)' },
    ],
    standardMessage: 'Eelgrass beds are critical nursery habitat for juvenile salmon, forage fish, and Dungeness crab. They also sequester carbon and stabilize shoreline sediments. Development or activity that disturbs eelgrass is regulated under the Shoreline Management Act.',
    placeholder: true,
  },
  {
    id: 'shoreline-types',
    name: 'Shoreline Types',
    description: 'Classification of shoreline character and substrate',
    category: 'ecological',
    source: '/data/shoreline_types.geojson',
    visible: true,
    style: {
      fillColor: '#0D4F4F',
      fillOpacity: 0,
      strokeColor: '#0D4F4F',
      strokeWeight: 2,
    },
    popupFields: [
      { key: 'shore_type', label: 'Shoreline Type' },
      { key: 'substrate', label: 'Substrate' },
    ],
    standardMessage: 'Shoreline character—whether rocky, sandy, or mixed—determines what species can thrive there. Armoring or modifying natural shorelines disrupts sediment transport and eliminates habitat for forage fish spawning.',
    placeholder: true,
  },
  {
    id: 'habitat-zones',
    name: 'Habitat Zones',
    description: 'Sensitive habitat areas identified through conservation research',
    category: 'ecological',
    source: '/data/habitat_zones.geojson',
    visible: true,
    style: {
      fillColor: '#D4A574',
      fillOpacity: 0.3,
      strokeColor: '#B8865A',
      strokeWeight: 1,
    },
    popupFields: [
      { key: 'habitat_type', label: 'Habitat Type' },
      { key: 'species', label: 'Key Species' },
      { key: 'sensitivity', label: 'Sensitivity' },
    ],
    standardMessage: 'These zones have been identified as ecologically sensitive through surveys and conservation research. Activities in or near these areas may require additional review under local critical areas ordinances.',
    placeholder: true,
  },

  // === Friends of the San Juans Data ===
  // -- Habitat --
  {
    id: 'friends-herring-spawning',
    name: 'Herring Spawning Grounds',
    description: 'Areas (present or historic) where Pacific Herring spawn (WDFW)',
    category: 'friends-data',
    source: '/data/friends-herring-spawning.json',
    visible: false,
    style: {
      fillColor: '#DAA520',
      fillOpacity: 0.35,
      strokeColor: '#B8860B',
      strokeWeight: 1.5,
    },
    popupFields: [
      { key: 'Name', label: 'Name' },
      { key: 'OBJECTID', label: 'Object ID' },
    ],
    standardMessage: 'Areas (either present or historic) where Pacific Herring spawn. Data from the WA Department of Fish and Wildlife. Herring are a keystone forage fish species, spawning on eelgrass and algae in nearshore areas and serving as a primary food source for salmon, seabirds, and marine mammals.',
  },
  {
    id: 'friends-bull-kelp',
    name: 'Bull Kelp',
    description: 'Canopy/floating kelp mapping (DNR and Friends)',
    category: 'friends-data',
    source: 'https://storage.googleapis.com/salish-ndvi-tiles/data/friends-bull-kelp.json',
    visible: false,
    style: {
      fillColor: '#6B8E23',
      fillOpacity: 0.5,
      strokeColor: '#556B2F',
      strokeWeight: 0.5,
    },
    popupFields: [
      { key: 'GRIDCODE', label: 'Grid Code' },
      { key: 'Area', label: 'Area' },
      { key: 'Acres', label: 'Acres' },
      { key: 'Hectares', label: 'Hectares' },
    ],
    standardMessage: 'Canopy, or floating kelp mapping completed by the WA Department of Natural Resources and Friends. Note: there are also many species of understory kelps along rocky shores that have not been mapped. Bull kelp forests provide critical habitat for rockfish, lingcod, and invertebrates.',
    minZoom: 15,
    viewportFiltered: true,
  },
  {
    id: 'friends-deepwater-eelgrass',
    name: 'Deepwater/Edge Eelgrass',
    description: 'Deepest (waterward) edge of eelgrass meadows (Friends, DNR, Friday Harbor Labs)',
    category: 'friends-data',
    source: '/data/friends-deepwater-eelgrass.geojson',
    visible: false,
    markerIcon: '/eelgrass-marker.png',
    style: {
      fillColor: '#20B2AA',
      fillOpacity: 0,
      strokeColor: '#20B2AA',
      strokeWeight: 2.5,
    },
    popupFields: [
      { key: 'SITE', label: 'Site' },
      { key: 'ISLAND', label: 'Island' },
      { key: 'MEAN', label: 'Mean Depth' },
      { key: 'MAX_', label: 'Max Depth' },
      { key: 'MIN_', label: 'Min Depth' },
      { key: 'SAMP_SIZE', label: 'Sample Size' },
      { key: 'COMMENTS', label: 'Comments' },
    ],
    standardMessage: 'The deepest (waterward) edge of eelgrass meadows based on a countywide study done by Friends, WA Department of Natural Resources, and Friday Harbor Labs.',
  },
  {
    id: 'friends-potential-forage-spawning',
    name: 'Potential Forage Fish Spawning',
    description: 'Beach substrate suitable to support spawning by Pacific sand lance or surf smelt',
    category: 'friends-data',
    source: '/data/friends-potential-forage-spawning.json',
    visible: false,
    style: {
      fillColor: '#FF7F50',
      fillOpacity: 0,
      strokeColor: '#FF7F50',
      strokeWeight: 2.5,
    },
    popupFields: [
      { key: 'C_Type_FOSJ', label: 'Shore Type' },
      { key: 'ShoreForm_Unit_ID', label: 'Shoreform Unit' },
    ],
    standardMessage: 'Beach substrate is suitable (non-bedrock shores) to support spawning by Pacific sand lance or surf smelt. Identified by Friends of the San Juans based on substrate and shoreline character.',
  },
  {
    id: 'friends-documented-forage-spawning',
    name: 'Documented Forage Fish Spawning',
    description: 'Beaches where Pacific sand lance, surf smelt, or both have been found spawning',
    category: 'friends-data',
    source: '/data/friends-documented-forage-spawning.json',
    visible: false,
    style: {
      fillColor: '#FF4500',
      fillOpacity: 0,
      strokeColor: '#FF4500',
      strokeWeight: 3,
    },
    popupFields: [
      { key: 'NAME', label: 'Beach Name' },
      { key: 'ISLAND', label: 'Island' },
      { key: 'SPECIES', label: 'Species' },
      { key: 'SMELT_IND', label: 'Smelt' },
      { key: 'SAND_LANCE_IND', label: 'Sand Lance' },
      { key: 'EggCount', label: 'Egg Count' },
      { key: 'RecordsSource', label: 'Source' },
    ],
    standardMessage: 'Pacific sand lance, Surf smelt, or both found at a specific beach. Confirmed through egg surveys by Friends of the San Juans.',
  },
  // -- Shoreline --
  {
    id: 'friends-shoreline-geology',
    name: 'Shoreline Geology',
    description: 'Primary geologic features of marine shorelines — coastal processes affect different shore form types in different ways, resulting in different management concerns and priorities',
    category: 'friends-data',
    source: '/data/friends-shoreline-geology.json',
    visible: false,
    style: {
      fillColor: '#708090',
      fillOpacity: 0,
      strokeColor: '#708090',
      strokeWeight: 2,
    },
    popupFields: [
      { key: 'ShoreForm_Unit_ID', label: 'Shoreform Unit' },
      { key: 'FFhab', label: 'Forage Fish Habitat' },
      { key: 'LandUse', label: 'Land Use' },
      { key: 'ShoreDESIG', label: 'Shore Designation' },
      { key: 'PIATprotection', label: 'Protection Priority' },
      { key: 'PIATrestoration', label: 'Restoration Priority' },
      { key: 'SLR_Protect', label: 'SLR Protection' },
      { key: 'SLR_Restore', label: 'SLR Restoration' },
    ],
    standardMessage: 'Shore form types include: Feeder Bluff Exceptional (highly erosive, important sediment source for down-drift beaches), Feeder Bluff (episodically erosive sediment source), Transport Zone (sediment moves through from supply bluffs to accretionary beaches), Barrier Beach (wide beaches where sediment is deposited), Pocket Beach (sand/gravel between rocky headlands with self-contained sediment), Embayment\u2013Estuary (closed bay with freshwater source), Embayment\u2013Lagoon (open or closed to marine environment, no consistent freshwater), Rocky Shoreline (lacks appreciable sediment drift or erosion), and Artificial (altered so much the historic shore type is unknown).',
  },
  {
    id: 'friends-armor',
    name: 'Shoreline Armor',
    description: 'Shoreline armoring — bulkheads, riprap, sea walls, bank stabilization installed to control erosion',
    category: 'friends-data',
    source: '/data/friends-armor.json',
    visible: false,
    style: {
      fillColor: '#8B0000',
      fillOpacity: 0,
      strokeColor: '#8B0000',
      strokeWeight: 3,
    },
    popupFields: [
      { key: 'Island', label: 'Island' },
      { key: 'ArmorLength', label: 'Armor Length' },
      { key: 'ArmorMaterial', label: 'Material' },
      { key: 'ArmorCondition', label: 'Condition' },
    ],
    standardMessage: 'Shoreline armoring also known as bulkheads, riprap, sea walls, bank stabilization \u2014 installed to control erosion (or sediment supply) from the bank. Armor disrupts natural sediment processes and eliminates forage fish spawning habitat.',
  },
  // -- Shoreline Infrastructure --
  {
    id: 'friends-groins',
    name: 'Groins',
    description: 'Structures perpendicular to shore, intended to trap alongshore sediment transport',
    category: 'friends-data',
    source: '/data/friends-groins.json',
    visible: false,
    style: {
      fillColor: '#8B4513',
      fillOpacity: 1,
      strokeColor: '#8B4513',
      strokeWeight: 1,
    },
    popupFields: [
      { key: 'Material', label: 'Material' },
      { key: 'Waypoint', label: 'Waypoint' },
      { key: 'CalculatedElevation', label: 'Elevation' },
    ],
    standardMessage: 'A structure that sticks out perpendicularly from shore, intended to trap the alongshore transport of sediment. Groins interrupt longshore sediment transport, starving downdrift beaches of material. Surveyed by Friends of the San Juans.',
  },
  {
    id: 'friends-boat-ramps',
    name: 'Boat Ramps',
    description: 'Concrete or other structural boat ramps across inter- and subtidal habitats',
    category: 'friends-data',
    source: '/data/friends-boat-ramps.json',
    visible: false,
    style: {
      fillColor: '#4682B4',
      fillOpacity: 1,
      strokeColor: '#4682B4',
      strokeWeight: 1,
    },
    popupFields: [
      { key: 'Waypoint', label: 'Waypoint' },
      { key: 'SurveyDate', label: 'Survey Date' },
    ],
    standardMessage: 'Concrete or other structural boat ramps across the inter- and subtidal habitats. Surveyed by Friends of the San Juans.',
  },
  {
    id: 'friends-marine-railway',
    name: 'Marine Railways',
    description: 'Typically elevated boat ramp structures',
    category: 'friends-data',
    source: '/data/friends-marine-railway.json',
    visible: false,
    style: {
      fillColor: '#2F4F4F',
      fillOpacity: 1,
      strokeColor: '#2F4F4F',
      strokeWeight: 1,
    },
    popupFields: [
      { key: 'waypoint', label: 'Waypoint' },
      { key: 'Surveytime', label: 'Survey Time' },
    ],
    standardMessage: 'Typically elevated boat ramp structures. Surveyed by Friends of the San Juans.',
  },
  {
    id: 'friends-mooring-buoys',
    name: 'Mooring Buoys & Floats',
    description: 'In and overwater moorage facilities',
    category: 'friends-data',
    source: '/data/friends-mooring-buoys.json',
    visible: false,
    markerIcon: '/buoy-marker.png',
    style: {
      fillColor: '#191970',
      fillOpacity: 1,
      strokeColor: '#191970',
      strokeWeight: 1,
    },
    popupFields: [
      { key: 'Type', label: 'Type' },
      { key: 'OBJECTID', label: 'Object ID' },
    ],
    standardMessage: 'In and overwater moorage facilities. Surveyed by Friends of the San Juans.',
  },
  {
    id: 'friends-pilings',
    name: 'Pilings',
    description: 'Pilings not associated with a dock or marina',
    category: 'friends-data',
    source: '/data/friends-pilings.json',
    visible: false,
    style: {
      fillColor: '#A0522D',
      fillOpacity: 1,
      strokeColor: '#A0522D',
      strokeWeight: 1,
    },
    popupFields: [
      { key: 'Count_', label: 'Count' },
      { key: 'Creosote', label: 'Creosote' },
    ],
    standardMessage: 'Pilings not associated with a dock or marina. Creosote-treated pilings leach toxic compounds into the marine environment. Surveyed by Friends of the San Juans.',
  },
  {
    id: 'friends-docks',
    name: 'Docks',
    description: 'Smaller overwater structures (does not include marinas)',
    category: 'friends-data',
    source: '/data/friends-docks.geojson',
    visible: false,
    markerIcon: '/dock-marker.png',
    style: {
      fillColor: '#008B8B',
      fillOpacity: 1,
      strokeColor: '#008B8B',
      strokeWeight: 1,
    },
    popupFields: [
      { key: 'TYPE', label: 'Type' },
      { key: 'Material', label: 'Material' },
      { key: 'Condition', label: 'Condition' },
      { key: 'Creosote', label: 'Creosote' },
      { key: 'Grating', label: 'Grating' },
      { key: 'PierHeight', label: 'Pier Height' },
      { key: 'Waypoint', label: 'Waypoint' },
    ],
    standardMessage: 'Smaller overwater structures (note: this layer does not include marinas). Dock shading and creosote-treated materials can impact nearshore habitat quality. Surveyed by Friends of the San Juans.',
  },
  {
    id: 'friends-restoration-sites',
    name: 'Restoration Sites',
    description: 'Shoreline restoration site locations (Friends)',
    category: 'friends-data',
    source: '/data/friends-restoration-sites.json',
    visible: false,
    style: {
      strokeColor: '#2D9B27',
      strokeWeight: 3,
      strokeOpacity: 0.9,
    },
    popupFields: [
      { key: 'Island', label: 'Island' },
      { key: 'Notes', label: 'Notes' },
    ],
    standardMessage: 'Shoreline restoration sites surveyed by Friends of the San Juans.',
  },
  {
    id: 'friends-iow-structures',
    name: 'In/Over Water Structures',
    description: 'In and over water structure projects (Friends)',
    category: 'friends-data',
    source: '/data/friends-iow-structures.json',
    visible: false,
    style: {
      fillColor: '#0EA5E9',
      fillOpacity: 1,
      strokeColor: '#0369A1',
      strokeWeight: 1,
    },
    popupFields: [
      { key: 'ISLAND', label: 'Island' },
      { key: 'OWNER', label: 'Owner' },
      { key: 'HABITAT_TYPE', label: 'Habitat Type' },
      { key: 'PROJECT_TYPE', label: 'Project Type' },
      { key: 'DESCRIPTION', label: 'Description' },
      { key: 'AMOUNT', label: 'Amount' },
    ],
    standardMessage: 'In and over water structure projects documented by Friends of the San Juans.',
  },
  {
    id: 'friends-restoration-projects',
    name: 'Restoration Projects',
    description: 'Habitat restoration projects (Friends)',
    category: 'friends-data',
    source: '/data/friends-restoration-projects.json',
    visible: false,
    style: {
      fillColor: '#16A34A',
      fillOpacity: 1,
      strokeColor: '#15803D',
      strokeWeight: 1,
    },
    popupFields: [
      { key: 'NAME', label: 'Name' },
      { key: 'ISLAND', label: 'Island' },
      { key: 'HABITAT_TYPE', label: 'Habitat Type' },
      { key: 'DATE', label: 'Date' },
      { key: 'DESCRIPTION', label: 'Description' },
      { key: 'LINEARFEET_SHORELINE', label: 'Linear Feet of Shoreline' },
      { key: 'ACRES_PROTECTED', label: 'Acres Protected' },
      { key: 'SQFT_HABITATRESTORED', label: 'Sq Ft Habitat Restored' },
      { key: 'LINK', label: 'Link' },
    ],
    standardMessage: 'Habitat restoration projects completed by Friends of the San Juans, including shoreline armor removal, riparian planting, and habitat enhancement.',
  },
  {
    id: 'friends-riparian-projects',
    name: 'Riparian Projects',
    description: 'Riparian restoration projects (Friends)',
    category: 'friends-data',
    source: '/data/friends-riparian-projects.json',
    visible: false,
    style: {
      fillColor: '#65A30D',
      fillOpacity: 1,
      strokeColor: '#4D7C0F',
      strokeWeight: 1,
    },
    popupFields: [
      { key: 'NAME', label: 'Name' },
      { key: 'ISLAND', label: 'Island' },
      { key: 'HABITAT_TYPE', label: 'Habitat Type' },
      { key: 'DESCRIPTION', label: 'Description' },
    ],
    standardMessage: 'Riparian restoration projects by Friends of the San Juans, focused on improving streamside and shoreline vegetation.',
  },
  {
    id: 'friends-armor-change-2019',
    name: 'Armor Change Analysis (2019)',
    description: 'Shoreline armor change analysis (Friends 2019)',
    category: 'friends-data',
    source: '/data/friends-armor-change-2019.json',
    visible: false,
    style: {
      strokeColor: '#DC2626',
      strokeWeight: 2.5,
      strokeOpacity: 0.8,
    },
    styleByProperty: {
      property: 'Year_originalArmorMapping',
      values: {
        '2009': { strokeColor: '#F59E0B', strokeWeight: 2.5 },
        '2019': { strokeColor: '#DC2626', strokeWeight: 3 },
      },
    },
    popupFields: [
      { key: 'Armor_ID', label: 'Armor ID' },
      { key: 'Year_originalArmorMapping', label: 'Year Originally Mapped' },
      { key: 'ConditionArmor', label: 'Condition' },
      { key: 'ArmorContainsRock', label: 'Contains Rock' },
      { key: 'ArmorContainsConcrete', label: 'Contains Concrete' },
      { key: 'ArmorContainsWood', label: 'Contains Wood' },
      { key: 'ArmorContainsCreosotesWood', label: 'Contains Creosote' },
      { key: 'TidalElev_Armor', label: 'Tidal Elevation' },
    ],
    standardMessage: 'Shoreline armor change analysis: amber segments were mapped in 2009, red segments are new armor identified in 2019. Data from Friends of the San Juans shoreline surveys.',
  },
  {
    id: 'friends-armor-2019',
    name: 'Shoreline Armor (2019)',
    description: 'Shoreline armor survey (Friends 2019)',
    category: 'friends-data',
    source: '/data/friends-armor-2019.json',
    visible: false,
    style: {
      strokeColor: '#B91C1C',
      strokeWeight: 2.5,
      strokeOpacity: 0.8,
    },
    popupFields: [
      { key: 'Island', label: 'Island' },
      { key: 'Notes', label: 'Notes' },
      { key: 'ConditionArmor', label: 'Condition' },
      { key: 'ArmorContainsRock', label: 'Contains Rock' },
      { key: 'ArmorContainsConcrete', label: 'Contains Concrete' },
      { key: 'ArmorContainsWood', label: 'Contains Wood' },
      { key: 'ArmorContainsCreosotesWood', label: 'Contains Creosote' },
      { key: 'TidalElev_Armor', label: 'Tidal Elevation' },
    ],
    standardMessage: 'Shoreline armoring also known as bulkheads, riprap, sea walls, bank stabilization \u2014 installed to control erosion (or sediment supply) from the bank. Surveyed by Friends of the San Juans in 2019.',
  },

  // === Community Science Layers ===
  {
    // Multi-source point observations of marbled murrelet. The runtime
    // category tree slots this under `species` (Species of Interest); the
    // `community-science` category here is a code-side fallback the
    // tree-fetch loader uses if the live tree is unreachable. The sentinel
    // `source: 'observations:multi'` tells useLayers to dispatch to
    // fetchSpeciesObservationsGeoJSON instead of treating the string as a
    // URL. The fetcher pulls GBIF + iNaturalist + eBird in parallel,
    // dedupes GBIF rows whose origin is iNaturalist, and returns Points
    // with a unified property schema (see SpeciesObservationProperties).
    // The popup is rendered by the layer-specific click handler, not the
    // generic popupFields machinery — so popupFields is left empty.
    id: 'marbled-murrelet-observations',
    name: 'Marbled Murrelet Observations',
    description: 'Photographed and checklist observations of marbled murrelet from GBIF, iNaturalist, and eBird — defaults to the last year.',
    category: 'community-science',
    source: 'observations:multi',
    species: {
      gbifKey: 5229281,
      inatTaxonId: 4531,
      ebirdCode: 'marmur',
      scientificName: 'Brachyramphus marmoratus',
      commonName: 'Marbled Murrelet',
      // 200 km covers the full Salish Sea from Olympia to Vancouver to
      // Sooke. iNat alone has ~235 MAMU records in this radius over the
      // past year; the prior 80 km default dropped south Puget Sound.
      defaultRadiusKm: 200,
      defaultDaysBack: 365,
    },
    visible: false,
    style: {
      fillColor: '#FF6A00',
      fillOpacity: 1,
      strokeColor: '#FFFFFF',
      strokeWeight: 1.5,
    },
    popupFields: [],
    standardMessage:
      'Marbled murrelets are listed as Threatened under the federal Endangered Species Act. Markers combine three sources: GBIF (global biodiversity records), iNaturalist (photo-verified citizen science), and eBird (recent checklists, last 30 days only). GBIF rows whose origin is iNaturalist are filtered out to avoid duplicates. Click any marker for the source observation page and photo (when available); drag the slider handles to narrow the date window.',
    sourceUrl: 'https://www.gbif.org/species/5229281',
  },
  {
    id: 'ebird-hotspots',
    name: 'eBird Hotspots',
    description: 'Birding hotspot locations from eBird (Cornell Lab of Ornithology)',
    category: 'community-science',
    source: 'ebird:hotspots',
    visible: false,
    markerIcon: '/bird-marker.png',
    style: {
      fillColor: '#E63946',
      fillOpacity: 1,
      strokeColor: '#E63946',
      strokeWeight: 1,
    },
    popupFields: [
      { key: 'locName', label: 'Location' },
      { key: 'numSpeciesAllTime', label: 'Species Recorded' },
      { key: 'numChecklistsAllTime', label: 'Checklists' },
      { key: 'latestObsDt', label: 'Latest Observation' },
    ],
    standardMessage: 'eBird hotspots are locations where birders regularly submit checklists. Click a hotspot on the map to view its full eBird report.',
  },
];

// Category labels and order are now sourced at runtime from the editable
// category tree at gs://salish-ndvi-tiles/config/category-tree.json.
// See src/services/categoryTree.ts. A baked-in fallback there keeps
// the sidebar working if the live fetch fails.
