import type { LayerConfig } from '../types';

export const layerConfigs: LayerConfig[] = [
  // === Property Layers ===
  {
    id: 'tax-parcels',
    name: 'Tax Parcels',
    description: 'Property boundaries from San Juan County Assessor',
    category: 'property',
    source: '/data/Tax_Parcels.geojson',
    visible: true,
    style: {
      fillColor: '#ADB5BD',
      fillOpacity: 0.05,
      strokeColor: '#F97316',
      strokeWeight: 1.2,
    },
    popupFields: [
      { key: 'PIN', label: 'Parcel ID' },
      { key: 'Short_Lega', label: 'Legal Description' },
      { key: 'Acres', label: 'Acres' },
      { key: 'Tax_Area', label: 'Tax Area' },
      { key: 'Land_Value', label: 'Land Value' },
      { key: 'Appraised_', label: 'Appraised Value' },
      { key: 'Bldg_Value', label: 'Building Value' },
      { key: 'Use_Code', label: 'Use Code' },
      { key: 'Descriptio', label: 'Description' },
      { key: 'Sale_date', label: 'Last Sale Date' },
      { key: 'Sale_Price', label: 'Last Sale Price' },
    ],
    minZoom: 15,
    viewportFiltered: true,
  },
  {
    id: 'building-footprints',
    name: 'Building Footprints',
    description: 'Building footprints across San Juan County',
    category: 'property',
    source: '/data/Building_Footprints.geojson',
    visible: true,
    style: {
      fillColor: '#60A5FA',
      fillOpacity: 0.7,
      strokeColor: '#1A252F',
      strokeWeight: 0.8,
    },
    popupFields: [
      { key: 'ADDRESS', label: 'Address' },
      { key: 'Sq_Ft', label: 'Footprint (sq ft)' },
      { key: 'Island', label: 'Island' },
      { key: 'PIN', label: 'Parcel PIN' },
      { key: 'Discriptio', label: 'Description' },
      { key: 'Source', label: 'Data Source' },
    ],
    minZoom: 15,
    viewportFiltered: true,
  },

  // === Planning Layers ===
  {
    id: 'stormwater-pipes',
    name: 'Stormwater Infrastructure',
    description: 'County stormwater pipe network',
    category: 'planning',
    source: '/data/Stormwater_Pipes.geojson',
    visible: true,
    minZoom: 15,
    style: {
      fillColor: '#E67E22',
      fillOpacity: 0,
      strokeColor: '#E67E22',
      strokeWeight: 2.5,
    },
    popupFields: [
      { key: 'Pipe_ID', label: 'Pipe ID' },
      { key: 'Diameter', label: 'Diameter (in)' },
      { key: 'Material', label: 'Material' },
      { key: 'Length', label: 'Length (ft)' },
      { key: 'Pipe_Class', label: 'Class' },
      { key: 'Island', label: 'Island' },
      { key: 'Status', label: 'Status' },
      { key: 'Instl_Year', label: 'Install Year' },
    ],
    standardMessage: 'Stormwater infrastructure carries runoff from roads and developed areas to nearby water bodies. Pollutants in stormwater—oils, heavy metals, nutrients—can degrade nearshore habitat quality for salmon, forage fish, and shellfish.',
  },

  // === Fish Habitat Layers ===
  {
    id: 'chinook-salmon',
    name: 'Chinook Salmon',
    description: 'Shoreline habitat relevance for Chinook salmon',
    category: 'fish-habitat',
    source: '/data/chinook-salmon.geojson',
    visible: false,
    style: {
      fillColor: '#DC2626',
      fillOpacity: 0,
      strokeColor: '#DC2626',
      strokeWeight: 2.5,
    },
    popupFields: [
      { key: 'Name', label: 'Location' },
      { key: 'HRM_Ck', label: 'Habitat Relevance (High)' },
      { key: 'LRM_Ck', label: 'Habitat Relevance (Low)' },
      { key: 'GeoUnit', label: 'Geomorphic Unit' },
      { key: 'RITT_SysTy', label: 'System Type' },
      { key: 'RITT_SubTy', label: 'Sub Type' },
    ],
    standardMessage: 'Chinook salmon are listed as threatened under the Endangered Species Act. Nearshore habitat is critical for juvenile Chinook rearing and migration. Shoreline modification can reduce prey availability and disrupt migration corridors.',
  },
  {
    id: 'chum-salmon',
    name: 'Chum Salmon',
    description: 'Shoreline habitat relevance for Chum salmon',
    category: 'fish-habitat',
    source: '/data/chum-salmon.geojson',
    visible: false,
    style: {
      fillColor: '#7C3AED',
      fillOpacity: 0,
      strokeColor: '#7C3AED',
      strokeWeight: 2.5,
    },
    popupFields: [
      { key: 'Name', label: 'Location' },
      { key: 'HRM_Chum', label: 'Habitat Relevance (High)' },
      { key: 'LRM_Chum', label: 'Habitat Relevance (Low)' },
      { key: 'GeoUnit', label: 'Geomorphic Unit' },
      { key: 'RITT_SysTy', label: 'System Type' },
      { key: 'RITT_SubTy', label: 'Sub Type' },
    ],
    standardMessage: 'Chum salmon depend on nearshore habitats during early marine life stages. Estuaries and pocket beaches provide critical transition zones where juveniles feed and grow before moving offshore.',
  },
  {
    id: 'pink-salmon',
    name: 'Pink Salmon',
    description: 'Shoreline habitat relevance for Pink salmon',
    category: 'fish-habitat',
    source: '/data/pink-salmon.geojson',
    visible: false,
    style: {
      fillColor: '#EC4899',
      fillOpacity: 0,
      strokeColor: '#EC4899',
      strokeWeight: 2.5,
    },
    popupFields: [
      { key: 'Name', label: 'Location' },
      { key: 'HRM_Pk', label: 'Habitat Relevance (High)' },
      { key: 'LRM_Pk', label: 'Habitat Relevance (Low)' },
      { key: 'GeoUnit', label: 'Geomorphic Unit' },
      { key: 'RITT_SysTy', label: 'System Type' },
      { key: 'RITT_SubTy', label: 'Sub Type' },
    ],
    standardMessage: 'Pink salmon are the most abundant Pacific salmon species. Their juveniles spend minimal time in freshwater, making nearshore marine habitat especially critical during outmigration.',
  },
  {
    id: 'pacific-herring',
    name: 'Pacific Herring',
    description: 'Shoreline habitat relevance for Pacific herring',
    category: 'fish-habitat',
    source: '/data/pacific-herring.geojson',
    visible: false,
    style: {
      fillColor: '#EAB308',
      fillOpacity: 0,
      strokeColor: '#EAB308',
      strokeWeight: 2.5,
    },
    popupFields: [
      { key: 'Name', label: 'Location' },
      { key: 'HRM_Herr', label: 'Habitat Relevance (High)' },
      { key: 'LRM_Herr', label: 'Habitat Relevance (Low)' },
      { key: 'GeoUnit', label: 'Geomorphic Unit' },
      { key: 'RITT_SysTy', label: 'System Type' },
      { key: 'RITT_SubTy', label: 'Sub Type' },
    ],
    standardMessage: 'Pacific herring are a keystone forage fish species, spawning on eelgrass and algae in nearshore areas. Herring are a primary food source for salmon, seabirds, and marine mammals throughout the Salish Sea.',
  },
  {
    id: 'pacific-sand-lance',
    name: 'Pacific Sand Lance',
    description: 'Shoreline habitat relevance for Pacific sand lance',
    category: 'fish-habitat',
    source: '/data/pacific-sand-lance.geojson',
    visible: false,
    style: {
      fillColor: '#F97316',
      fillOpacity: 0,
      strokeColor: '#F97316',
      strokeWeight: 2.5,
    },
    popupFields: [
      { key: 'Name', label: 'Location' },
      { key: 'HRM_Lance', label: 'Habitat Relevance (High)' },
      { key: 'LRM_Lance', label: 'Habitat Relevance (Low)' },
      { key: 'GeoUnit', label: 'Geomorphic Unit' },
      { key: 'RITT_SysTy', label: 'System Type' },
      { key: 'RITT_SubTy', label: 'Sub Type' },
    ],
    standardMessage: 'Sand lance spawn in the upper intertidal zone on sand-gravel beaches. Shoreline armoring and beach modification directly destroy spawning habitat for this essential forage fish.',
  },
  {
    id: 'surf-smelt',
    name: 'Surf Smelt',
    description: 'Shoreline habitat relevance for Surf smelt',
    category: 'fish-habitat',
    source: '/data/surf-smelt.geojson',
    visible: false,
    style: {
      fillColor: '#06B6D4',
      fillOpacity: 0,
      strokeColor: '#06B6D4',
      strokeWeight: 2.5,
    },
    popupFields: [
      { key: 'Name', label: 'Location' },
      { key: 'HRM_Smelt', label: 'Habitat Relevance (High)' },
      { key: 'LRM_Smelt', label: 'Habitat Relevance (Low)' },
      { key: 'GeoUnit', label: 'Geomorphic Unit' },
      { key: 'RITT_SysTy', label: 'System Type' },
      { key: 'RITT_SubTy', label: 'Sub Type' },
    ],
    standardMessage: 'Surf smelt spawn on mixed sand-gravel beaches in the upper intertidal zone. Like sand lance, their spawning habitat is directly threatened by shoreline hardening and development.',
  },
  {
    id: 'lingcod-greenling',
    name: 'Lingcod & Greenling',
    description: 'Shoreline habitat relevance for Lingcod and Greenling (Hexagrammidae)',
    category: 'fish-habitat',
    source: '/data/lingcod-greenling.geojson',
    visible: false,
    style: {
      fillColor: '#65A30D',
      fillOpacity: 0,
      strokeColor: '#65A30D',
      strokeWeight: 2.5,
    },
    popupFields: [
      { key: 'Name', label: 'Location' },
      { key: 'HRM_Hex', label: 'Habitat Relevance (High)' },
      { key: 'LRM_Hex', label: 'Habitat Relevance (Low)' },
      { key: 'GeoUnit', label: 'Geomorphic Unit' },
      { key: 'RITT_SysTy', label: 'System Type' },
      { key: 'RITT_SubTy', label: 'Sub Type' },
    ],
    standardMessage: 'Lingcod and greenling use rocky nearshore habitats for spawning and juvenile rearing. Kelp forests and rocky reefs are essential for their life cycle.',
  },

  // === Ecological Layers ===
  {
    id: 'ndvi',
    name: 'Vegetation Health (NDVI)',
    description: 'Normalized Difference Vegetation Index derived from NAIP aerial imagery (Oct 2023, 0.6m resolution)',
    category: 'ecological',
    source: '',
    visible: false,
    style: {
      fillColor: '#1a9850',
      fillOpacity: 0,
      strokeColor: '#1a9850',
      strokeWeight: 0,
    },
    popupFields: [],
    standardMessage: 'NDVI measures vegetation density and health from aerial imagery. Green areas indicate healthy, dense vegetation; yellow indicates sparse or stressed vegetation; red indicates bare ground, water, or impervious surfaces.',
    layerType: 'raster',
    tileUrl: 'https://storage.googleapis.com/salish-ndvi-tiles/ndvi/{z}/{x}/{y}.png',
    defaultOpacity: 0.7,
    minZoom: 10,
  },
  {
    id: 'ndvi-sentinel',
    name: 'Sentinel-2 NDVI (10m)',
    description: 'Sentinel-2 derived NDVI at 10m resolution — select a date range to view seasonal vegetation change',
    category: 'ecological',
    source: '',
    visible: false,
    style: {
      fillColor: '#1a9850',
      fillOpacity: 0,
      strokeColor: '#1a9850',
      strokeWeight: 0,
    },
    popupFields: [],
    standardMessage: 'Sentinel-2 NDVI computed on-the-fly from cloud-free satellite composites. Use the date range controls to compare vegetation health across seasons and years.',
    layerType: 'dynamic-raster',
    apiEndpoint: 'https://us-west1-salish-sea-property-mapper.cloudfunctions.net/ee-ndvi-tiles',
    defaultOpacity: 0.7,
    minZoom: 10,
  },
  {
    id: 'eelgrass',
    name: 'Eelgrass Beds',
    description: 'Mapped eelgrass (Zostera marina) presence in nearshore areas',
    category: 'ecological',
    source: '/data/eelgrass.geojson',
    visible: true,
    style: {
      fillColor: '#2D6A4F',
      fillOpacity: 0.4,
      strokeColor: '#1B4332',
      strokeWeight: 1,
    },
    popupFields: [
      { key: 'survey_year', label: 'Survey Year' },
      { key: 'density', label: 'Density Class' },
      { key: 'area_sqm', label: 'Area (sq m)' },
    ],
    standardMessage: 'Eelgrass beds are critical nursery habitat for juvenile salmon, forage fish, and Dungeness crab. They also sequester carbon and stabilize shoreline sediments. Development or activity that disturbs eelgrass is regulated under the Shoreline Management Act.',
    placeholder: true,
  },
  {
    id: 'shoreline-types',
    name: 'Shoreline Types',
    description: 'Classification of shoreline character and substrate',
    category: 'ecological',
    source: '/data/shoreline_types.geojson',
    visible: true,
    style: {
      fillColor: '#0D4F4F',
      fillOpacity: 0,
      strokeColor: '#0D4F4F',
      strokeWeight: 2,
    },
    popupFields: [
      { key: 'shore_type', label: 'Shoreline Type' },
      { key: 'substrate', label: 'Substrate' },
    ],
    standardMessage: 'Shoreline character—whether rocky, sandy, or mixed—determines what species can thrive there. Armoring or modifying natural shorelines disrupts sediment transport and eliminates habitat for forage fish spawning.',
    placeholder: true,
  },
  {
    id: 'habitat-zones',
    name: 'Habitat Zones',
    description: 'Sensitive habitat areas identified through conservation research',
    category: 'ecological',
    source: '/data/habitat_zones.geojson',
    visible: true,
    style: {
      fillColor: '#D4A574',
      fillOpacity: 0.3,
      strokeColor: '#B8865A',
      strokeWeight: 1,
    },
    popupFields: [
      { key: 'habitat_type', label: 'Habitat Type' },
      { key: 'species', label: 'Key Species' },
      { key: 'sensitivity', label: 'Sensitivity' },
    ],
    standardMessage: 'These zones have been identified as ecologically sensitive through surveys and conservation research. Activities in or near these areas may require additional review under local critical areas ordinances.',
    placeholder: true,
  },

  // === Friends of the San Juans Data ===
  // -- Habitat --
  {
    id: 'friends-herring-spawning',
    name: 'Herring Spawning Grounds',
    description: 'Pacific herring spawning grounds (WDFW 2004)',
    category: 'friends-data',
    source: '/data/friends-herring-spawning.json',
    visible: false,
    style: {
      fillColor: '#DAA520',
      fillOpacity: 0.35,
      strokeColor: '#B8860B',
      strokeWeight: 1.5,
    },
    popupFields: [
      { key: 'Name', label: 'Name' },
      { key: 'OBJECTID', label: 'Object ID' },
    ],
    standardMessage: 'Pacific herring spawning grounds mapped by WDFW in 2004. Herring spawn on eelgrass and algae in these nearshore areas.',
  },
  {
    id: 'friends-bull-kelp',
    name: 'Bull Kelp',
    description: 'Bull kelp canopy presence (DNR 2007)',
    category: 'friends-data',
    source: '/data/friends-bull-kelp.json',
    visible: false,
    style: {
      fillColor: '#6B8E23',
      fillOpacity: 0.5,
      strokeColor: '#556B2F',
      strokeWeight: 0.5,
    },
    popupFields: [
      { key: 'GRIDCODE', label: 'Grid Code' },
      { key: 'Area', label: 'Area' },
      { key: 'Acres', label: 'Acres' },
      { key: 'Hectares', label: 'Hectares' },
    ],
    standardMessage: 'Bull kelp canopy mapped from aerial imagery by DNR in 2007. Bull kelp forests provide critical habitat for rockfish, lingcod, and invertebrates.',
    minZoom: 15,
    viewportFiltered: true,
  },
  {
    id: 'friends-deepwater-eelgrass',
    name: 'Deepwater/Edge Eelgrass',
    description: 'Deepwater and edge eelgrass surveys (DNR/UW 2004)',
    category: 'friends-data',
    source: '/data/friends-deepwater-eelgrass.geojson',
    visible: false,
    markerIcon: '/eelgrass-marker.png',
    style: {
      fillColor: '#20B2AA',
      fillOpacity: 0,
      strokeColor: '#20B2AA',
      strokeWeight: 2.5,
    },
    popupFields: [
      { key: 'SITE', label: 'Site' },
      { key: 'ISLAND', label: 'Island' },
      { key: 'MEAN', label: 'Mean Depth' },
      { key: 'MAX_', label: 'Max Depth' },
      { key: 'MIN_', label: 'Min Depth' },
      { key: 'SAMP_SIZE', label: 'Sample Size' },
      { key: 'COMMENTS', label: 'Comments' },
    ],
    standardMessage: 'Deepwater and edge eelgrass transects surveyed by DNR and UW in 2004. These represent the deeper extent of eelgrass beds.',
  },
  {
    id: 'friends-potential-forage-spawning',
    name: 'Potential Forage Fish Spawning',
    description: 'Potential forage fish spawning habitat (Friends 2020)',
    category: 'friends-data',
    source: '/data/friends-potential-forage-spawning.json',
    visible: false,
    style: {
      fillColor: '#FF7F50',
      fillOpacity: 0,
      strokeColor: '#FF7F50',
      strokeWeight: 2.5,
    },
    popupFields: [
      { key: 'C_Type_FOSJ', label: 'Shore Type' },
      { key: 'ShoreForm_Unit_ID', label: 'Shoreform Unit' },
    ],
    standardMessage: 'Shoreline segments identified as potential forage fish spawning habitat by Friends of the San Juans in 2020, based on substrate and shoreline character.',
  },
  {
    id: 'friends-documented-forage-spawning',
    name: 'Documented Forage Fish Spawning',
    description: 'Documented forage fish spawning beaches (Friends 2022)',
    category: 'friends-data',
    source: '/data/friends-documented-forage-spawning.json',
    visible: false,
    style: {
      fillColor: '#FF4500',
      fillOpacity: 0,
      strokeColor: '#FF4500',
      strokeWeight: 3,
    },
    popupFields: [
      { key: 'NAME', label: 'Beach Name' },
      { key: 'ISLAND', label: 'Island' },
      { key: 'SPECIES', label: 'Species' },
      { key: 'SMELT_IND', label: 'Smelt' },
      { key: 'SAND_LANCE_IND', label: 'Sand Lance' },
      { key: 'EggCount', label: 'Egg Count' },
      { key: 'RecordsSource', label: 'Source' },
    ],
    standardMessage: 'Beaches where forage fish spawning (surf smelt and/or sand lance) has been confirmed through egg surveys by Friends of the San Juans through 2022.',
  },
  // -- Shoreline --
  {
    id: 'friends-shoreline-geology',
    name: 'Shoreline Geology',
    description: 'Shoreline geology and process classification (CGS 2012)',
    category: 'friends-data',
    source: '/data/friends-shoreline-geology.json',
    visible: false,
    style: {
      fillColor: '#708090',
      fillOpacity: 0,
      strokeColor: '#708090',
      strokeWeight: 2,
    },
    popupFields: [
      { key: 'ShoreForm_Unit_ID', label: 'Shoreform Unit' },
      { key: 'FFhab', label: 'Forage Fish Habitat' },
      { key: 'LandUse', label: 'Land Use' },
      { key: 'ShoreDESIG', label: 'Shore Designation' },
      { key: 'PIATprotection', label: 'Protection Priority' },
      { key: 'PIATrestoration', label: 'Restoration Priority' },
      { key: 'SLR_Protect', label: 'SLR Protection' },
      { key: 'SLR_Restore', label: 'SLR Restoration' },
    ],
    standardMessage: 'Shoreline geology and geomorphic classification from the Coastal Geologic Services 2012 assessment. Includes protection and restoration prioritization.',
  },
  {
    id: 'friends-armor',
    name: 'Shoreline Armor',
    description: 'Shoreline armoring survey (Friends 2019)',
    category: 'friends-data',
    source: '/data/friends-armor.json',
    visible: false,
    style: {
      fillColor: '#8B0000',
      fillOpacity: 0,
      strokeColor: '#8B0000',
      strokeWeight: 3,
    },
    popupFields: [
      { key: 'Island', label: 'Island' },
      { key: 'ArmorLength', label: 'Armor Length' },
      { key: 'ArmorMaterial', label: 'Material' },
      { key: 'ArmorCondition', label: 'Condition' },
    ],
    standardMessage: 'Shoreline armor (bulkheads, seawalls, riprap) surveyed by Friends of the San Juans in 2019. Armor disrupts natural sediment processes and eliminates forage fish spawning habitat.',
  },
  // -- Shoreline Infrastructure --
  {
    id: 'friends-groins',
    name: 'Groins',
    description: 'Groin structures (Friends 2009)',
    category: 'friends-data',
    source: '/data/friends-groins.json',
    visible: false,
    style: {
      fillColor: '#8B4513',
      fillOpacity: 1,
      strokeColor: '#8B4513',
      strokeWeight: 1,
    },
    popupFields: [
      { key: 'Material', label: 'Material' },
      { key: 'Waypoint', label: 'Waypoint' },
      { key: 'CalculatedElevation', label: 'Elevation' },
    ],
    standardMessage: 'Groin structures surveyed by Friends of the San Juans in 2009. Groins interrupt longshore sediment transport, starving downdrift beaches of material.',
  },
  {
    id: 'friends-boat-ramps',
    name: 'Boat Ramps',
    description: 'Improved boat ramps (Friends 2009)',
    category: 'friends-data',
    source: '/data/friends-boat-ramps.json',
    visible: false,
    style: {
      fillColor: '#4682B4',
      fillOpacity: 1,
      strokeColor: '#4682B4',
      strokeWeight: 1,
    },
    popupFields: [
      { key: 'Waypoint', label: 'Waypoint' },
      { key: 'SurveyDate', label: 'Survey Date' },
    ],
    standardMessage: 'Improved boat ramp locations surveyed by Friends of the San Juans in 2009.',
  },
  {
    id: 'friends-marine-railway',
    name: 'Marine Railways',
    description: 'Marine railway locations (Friends 2009)',
    category: 'friends-data',
    source: '/data/friends-marine-railway.json',
    visible: false,
    style: {
      fillColor: '#2F4F4F',
      fillOpacity: 1,
      strokeColor: '#2F4F4F',
      strokeWeight: 1,
    },
    popupFields: [
      { key: 'waypoint', label: 'Waypoint' },
      { key: 'Surveytime', label: 'Survey Time' },
    ],
    standardMessage: 'Marine railway locations surveyed by Friends of the San Juans in 2009.',
  },
  {
    id: 'friends-mooring-buoys',
    name: 'Mooring Buoys & Floats',
    description: 'Mooring buoys and floats (Friends 2009)',
    category: 'friends-data',
    source: '/data/friends-mooring-buoys.json',
    visible: false,
    markerIcon: '/buoy-marker.png',
    style: {
      fillColor: '#191970',
      fillOpacity: 1,
      strokeColor: '#191970',
      strokeWeight: 1,
    },
    popupFields: [
      { key: 'Type', label: 'Type' },
      { key: 'OBJECTID', label: 'Object ID' },
    ],
    standardMessage: 'Mooring buoy and float locations surveyed by Friends of the San Juans in 2009.',
  },
  {
    id: 'friends-pilings',
    name: 'Pilings',
    description: 'Piling locations (Friends 2009)',
    category: 'friends-data',
    source: '/data/friends-pilings.json',
    visible: false,
    style: {
      fillColor: '#A0522D',
      fillOpacity: 1,
      strokeColor: '#A0522D',
      strokeWeight: 1,
    },
    popupFields: [
      { key: 'Count_', label: 'Count' },
      { key: 'Creosote', label: 'Creosote' },
    ],
    standardMessage: 'Piling locations surveyed by Friends of the San Juans in 2009. Creosote-treated pilings leach toxic compounds into the marine environment.',
  },
  {
    id: 'friends-docks',
    name: 'Docks',
    description: 'Dock locations and conditions (Friends 2009)',
    category: 'friends-data',
    source: '/data/friends-docks.geojson',
    visible: false,
    markerIcon: '/dock-marker.png',
    style: {
      fillColor: '#008B8B',
      fillOpacity: 1,
      strokeColor: '#008B8B',
      strokeWeight: 1,
    },
    popupFields: [
      { key: 'TYPE', label: 'Type' },
      { key: 'Material', label: 'Material' },
      { key: 'Condition', label: 'Condition' },
      { key: 'Creosote', label: 'Creosote' },
      { key: 'Grating', label: 'Grating' },
      { key: 'PierHeight', label: 'Pier Height' },
      { key: 'Waypoint', label: 'Waypoint' },
    ],
    standardMessage: 'Dock structures surveyed by Friends of the San Juans in 2009. Dock shading and creosote-treated materials can impact nearshore habitat quality.',
  },

  // === Community Science Layers ===
  {
    id: 'ebird-hotspots',
    name: 'eBird Hotspots',
    description: 'Birding hotspot locations from eBird (Cornell Lab of Ornithology)',
    category: 'community-science',
    source: 'ebird:hotspots',
    visible: false,
    markerIcon: '/bird-marker.png',
    style: {
      fillColor: '#E63946',
      fillOpacity: 1,
      strokeColor: '#E63946',
      strokeWeight: 1,
    },
    popupFields: [
      { key: 'locName', label: 'Location' },
      { key: 'numSpeciesAllTime', label: 'Species Recorded' },
      { key: 'numChecklistsAllTime', label: 'Checklists' },
      { key: 'latestObsDt', label: 'Latest Observation' },
    ],
    standardMessage: 'eBird hotspots are locations where birders regularly submit checklists. Click a hotspot on the map to view its full eBird report.',
  },
];

export const categoryLabels: Record<string, string> = {
  'fish-habitat': 'Fish Habitat',
  ecological: 'Ecological',
  property: 'Property',
  'community-science': 'Community Science',
  planning: 'Planning & Infrastructure',
  'friends-data': "Friends of the San Juans",
};

export const categoryOrder = ['friends-data', 'fish-habitat', 'ecological', 'property', 'planning', 'community-science'];
